"""Finalize workflow: save images and insert into document."""

import logging
import os
import re
import tempfile
from typing import Literal

from ..config import IllustrateConfig
from ..schemas import ImageLocationPlan
from ..state import (
    FinalImage,
    IllustrateState,
    WorkflowError,
)
from ..utils import select_winning_results

logger = logging.getLogger(__name__)


def _insert_images_into_markdown(
    document: str,
    final_images: list[FinalImage],
    image_plan: list[ImageLocationPlan],
) -> str:
    """Insert image references into markdown below specified headers."""
    if not final_images:
        return document

    images_by_id = {img["location_id"]: img for img in final_images}

    lines = document.split("\n")
    insertions = []

    for plan in image_plan:
        if plan.location_id not in images_by_id:
            continue

        img = images_by_id[plan.location_id]
        header_text = plan.insertion_after_header

        header_line_idx = None
        for i, line in enumerate(lines):
            if re.match(r"^#+\s*" + re.escape(header_text) + r"\s*$", line.strip()):
                header_line_idx = i
                break
            if header_text in line and line.strip().startswith("#"):
                header_line_idx = i
                break

        if header_line_idx is None:
            logger.warning(f"Could not find header '{header_text}' for image {plan.location_id}")
            continue

        alt_text = img["alt_text"] or f"Image: {header_text}"
        file_path = img["file_path"]
        image_md = f"\n![{alt_text}]({file_path})\n"

        image_type = img.get("image_type", "generated")
        if image_type == "public_domain" and img.get("attribution"):
            attr = img["attribution"]
            photographer = attr.get("photographer", "Unknown")
            source = attr.get("source", "")
            source_url = attr.get("source_url", "")
            if source_url:
                image_md += f"\n*Photo by {photographer} via [{source}]({source_url})*\n"
            else:
                image_md += f"\n*Photo by {photographer} via {source}*\n"
        elif image_type == "diagram":
            image_md += "\n*Diagram generated by Claude*\n"
        elif image_type == "generated":
            image_md += "\n*Image generated by Imagen*\n"

        insertions.append((header_line_idx + 1, image_md))

    insertions.sort(key=lambda x: x[0], reverse=True)
    for line_idx, md in insertions:
        lines.insert(line_idx, md)

    return "\n".join(lines)


def _determine_status(
    image_plan: list[ImageLocationPlan],
    final_images: list[FinalImage],
    errors: list[WorkflowError],
    cut_location_ids: set[str] | None = None,
) -> Literal["success", "partial", "failed"]:
    """Determine workflow status based on results.

    Locations that were editorially cut are excluded from the expected
    set so they don't count as missing.
    """
    if not image_plan:
        return "failed"
    if not final_images:
        return "failed"
    expected = len(image_plan) - len(cut_location_ids) if cut_location_ids else len(image_plan)
    if expected <= 0:
        return "success" if final_images else "failed"
    if len(final_images) >= expected:
        return "success"
    return "partial"


async def finalize_node(state: IllustrateState) -> dict:
    """Finalize workflow: save images to files and insert into markdown.

    Uses selection_results to pick the winning image per location,
    then saves to disk and inserts references into the markdown document.

    Returns:
        State update with final_images, illustrated_document, status
    """
    config = state.get("config") or IllustrateConfig()
    document = state["input"]["markdown_document"]
    image_plan = state.get("image_plan", [])
    generation_results = state.get("generation_results", [])
    selection_results = state.get("selection_results", [])
    existing_errors = state.get("errors", [])

    # Get output directory
    output_dir = config.output_dir or state["input"].get("output_dir")
    if not output_dir:
        output_dir = tempfile.mkdtemp(prefix="illustrate_")
        logger.info(f"Using temp directory for images: {output_dir}")

    os.makedirs(output_dir, exist_ok=True)

    plans_by_id = {p.location_id: p for p in image_plan}

    # Pick winning results using selection_results
    approved = select_winning_results(generation_results, selection_results)

    # Filter out editorial cuts
    editorial_result = state.get("editorial_review_result")
    cut_ids: set[str] = set()
    if editorial_result:
        cut_ids = set(editorial_result.get("cut_location_ids", []))
        if cut_ids:
            before_count = len(approved)
            approved = [r for r in approved if r["location_id"] not in cut_ids]
            for cut_id in cut_ids:
                # Find cut reason from evaluations
                reason = "no reason given"
                for ev in editorial_result.get("evaluations", []):
                    if ev.get("location_id") == cut_id and ev.get("cut_reason"):
                        reason = ev["cut_reason"]
                        break
                logger.info(f"Editorial cut applied: {cut_id} — {reason}")
            logger.info(f"Editorial review: {before_count} → {len(approved)} images after cuts")

    logger.info(f"Finalizing {len(approved)} approved images")

    # Save images and build final_images list
    final_images: list[FinalImage] = []
    errors: list[WorkflowError] = []

    for gen_result in approved:
        location_id = gen_result["location_id"]
        plan = plans_by_id.get(location_id)

        if not plan:
            logger.warning(f"No plan found for {location_id}")
            continue

        if not gen_result["image_bytes"]:
            logger.warning(f"No image bytes for {location_id}")
            continue

        # Determine file extension
        image_type = gen_result["image_type"]
        ext = "png"
        if image_type == "public_domain":
            if gen_result["image_bytes"][:2] == b"\xff\xd8":
                ext = "jpg"

        filename = f"{location_id}.{ext}"
        file_path = os.path.join(output_dir, filename)

        try:
            with open(file_path, "wb") as f:
                f.write(gen_result["image_bytes"])
            logger.info(f"Saved image: {file_path}")

            final_images.append(
                FinalImage(
                    location_id=location_id,
                    insertion_after_header=plan.insertion_after_header,
                    file_path=file_path,
                    alt_text=gen_result["alt_text"] or f"Image: {plan.insertion_after_header}",
                    image_type=image_type,
                    attribution=gen_result["attribution"],
                )
            )

        except Exception as e:
            logger.error(f"Failed to save image {location_id}: {e}")
            errors.append(
                WorkflowError(
                    location_id=location_id,
                    severity="error",
                    message=f"Failed to save image: {e}",
                    stage="finalize",
                )
            )

    # Insert images into document
    illustrated_document = _insert_images_into_markdown(
        document=document,
        final_images=final_images,
        image_plan=image_plan,
    )

    # Determine status — exclude editorial cuts from the expected count
    all_errors = existing_errors + errors
    status = _determine_status(image_plan, final_images, all_errors, cut_ids or None)

    # Log dropped images
    planned_ids = {p.location_id for p in image_plan}
    approved_ids = {img["location_id"] for img in final_images}
    dropped_ids = planned_ids - approved_ids
    for loc_id in dropped_ids:
        logger.warning(f"Image dropped: {loc_id}")

    logger.info(f"Finalize complete: {len(final_images)}/{len(image_plan)} images, status={status}")

    return {
        "final_images": final_images,
        "illustrated_document": illustrated_document,
        "errors": errors,
        "status": status,
    }
