"""Finalize workflow: save images and insert into document."""

import logging
import os
import re
import tempfile
from collections import defaultdict
from typing import Literal

from ..config import IllustrateConfig
from ..schemas import ImageLocationPlan
from ..state import (
    FinalImage,
    ImageGenResult,
    IllustrateState,
    LocationSelection,
    WorkflowError,
)

logger = logging.getLogger(__name__)


def _select_winning_results(
    generation_results: list[ImageGenResult],
    selection_results: list[LocationSelection],
) -> list[ImageGenResult]:
    """Pick the winning ImageGenResult per location based on selection_results.

    For each location with a selection, find the generation result matching
    the selected_brief_id. Falls back to the last successful result if
    the selected brief_id can't be found.
    """
    # Build lookup: brief_id -> ImageGenResult
    results_by_brief_id: dict[str, ImageGenResult] = {}
    results_by_location: dict[str, list[ImageGenResult]] = defaultdict(list)
    for gen in generation_results:
        if gen["success"] and gen.get("image_bytes"):
            results_by_brief_id[gen["brief_id"]] = gen
            results_by_location[gen["location_id"]].append(gen)

    # Deduplicate selections: keep only the LAST entry per location_id.
    # selection_results uses an `add` reducer, so retry-round entries appear
    # after earlier rounds.  Without dedup the first (often "failed") entry
    # claims the slot and the retry success is silently skipped.
    latest_selection: dict[str, LocationSelection] = {}
    for selection in selection_results:
        latest_selection[selection["location_id"]] = selection

    winners: list[ImageGenResult] = []
    selected_locations: set[str] = set()

    for loc_id, selection in latest_selection.items():
        selected_locations.add(loc_id)

        if selection["quality_tier"] == "failed":
            continue  # Both candidates failed, no image for this location

        brief_id = selection["selected_brief_id"]
        if brief_id and brief_id in results_by_brief_id:
            winners.append(results_by_brief_id[brief_id])
        elif loc_id in results_by_location:
            # Fallback: use the last successful result for this location
            logger.warning(f"Selected brief_id {brief_id} not found for {loc_id}, using fallback")
            winners.append(results_by_location[loc_id][-1])

    # Also include any successful results for locations without selection
    # (e.g., from retry rounds that bypass selection)
    for loc_id, results in results_by_location.items():
        if loc_id not in selected_locations:
            winners.append(results[-1])

    return winners


def _insert_images_into_markdown(
    document: str,
    final_images: list[FinalImage],
    image_plan: list[ImageLocationPlan],
) -> str:
    """Insert image references into markdown below specified headers."""
    if not final_images:
        return document

    images_by_id = {img["location_id"]: img for img in final_images}

    lines = document.split("\n")
    insertions = []

    for plan in image_plan:
        if plan.location_id not in images_by_id:
            continue

        img = images_by_id[plan.location_id]
        header_text = plan.insertion_after_header

        header_line_idx = None
        for i, line in enumerate(lines):
            if re.match(r"^#+\s*" + re.escape(header_text) + r"\s*$", line.strip()):
                header_line_idx = i
                break
            if header_text in line and line.strip().startswith("#"):
                header_line_idx = i
                break

        if header_line_idx is None:
            logger.warning(f"Could not find header '{header_text}' for image {plan.location_id}")
            continue

        alt_text = img["alt_text"] or f"Image: {header_text}"
        file_path = img["file_path"]
        image_md = f"\n![{alt_text}]({file_path})\n"

        image_type = img.get("image_type", "generated")
        if image_type == "public_domain" and img.get("attribution"):
            attr = img["attribution"]
            photographer = attr.get("photographer", "Unknown")
            source = attr.get("source", "")
            source_url = attr.get("source_url", "")
            if source_url:
                image_md += f"\n*Photo by {photographer} via [{source}]({source_url})*\n"
            else:
                image_md += f"\n*Photo by {photographer} via {source}*\n"
        elif image_type == "diagram":
            image_md += "\n*Diagram generated by Claude*\n"
        elif image_type == "generated":
            image_md += "\n*Image generated by Imagen*\n"

        insertions.append((header_line_idx + 1, image_md))

    insertions.sort(key=lambda x: x[0], reverse=True)
    for line_idx, md in insertions:
        lines.insert(line_idx, md)

    return "\n".join(lines)


def _determine_status(
    image_plan: list[ImageLocationPlan],
    final_images: list[FinalImage],
    errors: list[WorkflowError],
) -> Literal["success", "partial", "failed"]:
    """Determine workflow status based on results."""
    if not image_plan:
        return "failed"
    if not final_images:
        return "failed"
    if len(final_images) == len(image_plan):
        return "success"
    return "partial"


async def finalize_node(state: IllustrateState) -> dict:
    """Finalize workflow: save images to files and insert into markdown.

    Uses selection_results to pick the winning image per location,
    then saves to disk and inserts references into the markdown document.

    Returns:
        State update with final_images, illustrated_document, status
    """
    config = state.get("config") or IllustrateConfig()
    document = state["input"]["markdown_document"]
    image_plan = state.get("image_plan", [])
    generation_results = state.get("generation_results", [])
    selection_results = state.get("selection_results", [])
    existing_errors = state.get("errors", [])

    # Get output directory
    output_dir = config.output_dir or state["input"].get("output_dir")
    if not output_dir:
        output_dir = tempfile.mkdtemp(prefix="illustrate_")
        logger.info(f"Using temp directory for images: {output_dir}")

    os.makedirs(output_dir, exist_ok=True)

    plans_by_id = {p.location_id: p for p in image_plan}

    # Pick winning results using selection_results
    approved = _select_winning_results(generation_results, selection_results)

    logger.info(f"Finalizing {len(approved)} approved images")

    # Save images and build final_images list
    final_images: list[FinalImage] = []
    errors: list[WorkflowError] = []

    for gen_result in approved:
        location_id = gen_result["location_id"]
        plan = plans_by_id.get(location_id)

        if not plan:
            logger.warning(f"No plan found for {location_id}")
            continue

        if not gen_result["image_bytes"]:
            logger.warning(f"No image bytes for {location_id}")
            continue

        # Determine file extension
        image_type = gen_result["image_type"]
        ext = "png"
        if image_type == "public_domain":
            if gen_result["image_bytes"][:2] == b"\xff\xd8":
                ext = "jpg"

        filename = f"{location_id}.{ext}"
        file_path = os.path.join(output_dir, filename)

        try:
            with open(file_path, "wb") as f:
                f.write(gen_result["image_bytes"])
            logger.info(f"Saved image: {file_path}")

            final_images.append(
                FinalImage(
                    location_id=location_id,
                    insertion_after_header=plan.insertion_after_header,
                    file_path=file_path,
                    alt_text=gen_result["alt_text"] or f"Image: {plan.insertion_after_header}",
                    image_type=image_type,
                    attribution=gen_result["attribution"],
                )
            )

        except Exception as e:
            logger.error(f"Failed to save image {location_id}: {e}")
            errors.append(
                WorkflowError(
                    location_id=location_id,
                    severity="error",
                    message=f"Failed to save image: {e}",
                    stage="finalize",
                )
            )

    # Insert images into document
    illustrated_document = _insert_images_into_markdown(
        document=document,
        final_images=final_images,
        image_plan=image_plan,
    )

    # Determine status
    all_errors = existing_errors + errors
    status = _determine_status(image_plan, final_images, all_errors)

    # Log dropped images
    planned_ids = {p.location_id for p in image_plan}
    approved_ids = {img["location_id"] for img in final_images}
    dropped_ids = planned_ids - approved_ids
    for loc_id in dropped_ids:
        logger.warning(f"Image dropped: {loc_id}")

    logger.info(f"Finalize complete: {len(final_images)}/{len(image_plan)} images, status={status}")

    return {
        "final_images": final_images,
        "illustrated_document": illustrated_document,
        "errors": errors,
        "status": status,
    }
