"""Utility functions for Loop 5 fact and reference checking."""

from workflows.shared.token_utils import (
    HAIKU_SAFE_LIMIT,
    SONNET_1M_SAFE_LIMIT,
    DEFAULT_RESPONSE_BUFFER,
)

HAIKU_MAX_TOKENS = HAIKU_SAFE_LIMIT
SONNET_1M_MAX_TOKENS = SONNET_1M_SAFE_LIMIT
SONNET_1M_THRESHOLD = 120_000
RESPONSE_BUFFER_TOKENS = DEFAULT_RESPONSE_BUFFER
