"""
Minimal schema definitions for Thala stores.

Key concepts:
- `id` (UUID): Primary key for ALL records across all stores
- `zotero_key`: Optional, only for externally-sourced content (books, web pages, etc.)
- Internal references always use UUID
"""

from datetime import datetime, timezone
from enum import Enum
from typing import Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, Field


def _utc_now() -> datetime:
    """Return current UTC datetime (timezone-aware)."""
    return datetime.now(timezone.utc)


class SourceType(str, Enum):
    """Origin of the record."""

    EXTERNAL = "external"  # Has a zotero_key
    INTERNAL = "internal"  # Generated by the system (coherence, compressions, etc.)


class BaseRecord(BaseModel):
    """Common fields for all store records."""

    id: UUID = Field(default_factory=uuid4)
    source_type: SourceType
    zotero_key: Optional[str] = Field(
        None,
        min_length=8,
        max_length=8,
        description="8-char Zotero key, only for external sources",
    )
    content: str = Field(description="Main text content for embedding")
    language_code: Optional[str] = Field(
        None,
        min_length=2,
        max_length=5,
        description="ISO 639-1 language code (e.g., 'en', 'es', 'zh')",
    )
    metadata: dict = Field(
        default_factory=dict,
        description="Flexible metadata (source, related topics, etc.)",
    )
    created_at: datetime = Field(default_factory=_utc_now)
    updated_at: datetime = Field(default_factory=_utc_now)
    embedding_model: Optional[str] = Field(
        None, description="Model used to generate embeddings, if any"
    )
    embedding: Optional[list[float]] = Field(
        None, description="Embedding vector for semantic search"
    )


class CoherenceRecord(BaseRecord):
    """
    Identity, beliefs, preferences with confidence scores.
    Always internal (generated by the system).
    """

    source_type: SourceType = SourceType.INTERNAL
    confidence: float = Field(ge=0.0, le=1.0)
    category: Optional[str] = Field(
        None, description="e.g., 'belief', 'preference', 'identity', 'goal'"
    )


class WhoIWasRecord(BaseRecord):
    """
    Edit history - temporal record of superseded beliefs/state.
    References internal UUIDs and stores snapshot of previous data.
    """

    source_type: SourceType = SourceType.INTERNAL
    supersedes: UUID = Field(description="UUID of the record this replaced")
    reason: Optional[str] = Field(None, description="Why this change occurred")
    previous_data: dict = Field(
        default_factory=dict, description="Snapshot of the record before change"
    )
    original_store: str = Field(description="Which store: 'coherence', 'top_of_mind'")


class StoreRecord(BaseRecord):
    """
    Main store - everything relevant, 10:1 compressions.
    Can be external (direct from Zotero) or internal (compressions).
    """

    compression_level: int = Field(
        default=0, ge=0, description="0 = original, 1+ = compression depth"
    )
    source_ids: list[UUID] = Field(
        default_factory=list,
        description="UUIDs this was derived from (for compressions)",
    )


class ForgottenRecord(BaseRecord):
    """
    Archived content with reason for forgetting.
    Preserves the original record structure and data snapshot.
    """

    forgotten_reason: str
    forgotten_at: datetime = Field(default_factory=_utc_now)
    original_store: str = Field(
        description="Which store this came from: 'coherence', 'store'"
    )
    previous_data: dict = Field(
        default_factory=dict, description="Snapshot of the record before forgetting"
    )
