"""Prompts for supervision loops - organized by loop number."""

# Re-export all prompts for backward compatibility
from .loop1_supervision import (
    INTEGRATOR_SYSTEM,
    INTEGRATOR_USER,
    SUPERVISOR_SYSTEM,
    SUPERVISOR_USER,
)
from .loop2_literature import (
    LOOP2_ANALYZER_SYSTEM,
    LOOP2_ANALYZER_USER,
    LOOP2_INTEGRATOR_SYSTEM,
    LOOP2_INTEGRATOR_USER,
)
from .loop3_structure import (
    LOOP3_ANALYST_SYSTEM,
    LOOP3_ANALYST_USER,
    LOOP3_EDITOR_SYSTEM,
    LOOP3_EDITOR_USER,
    LOOP3_PHASE_A_SYSTEM,
    LOOP3_PHASE_A_USER,
    LOOP3_PHASE_B_SYSTEM,
    LOOP3_PHASE_B_USER,
    LOOP3_RETRY_SYSTEM,
    LOOP3_VERIFIER_SYSTEM,
    LOOP3_VERIFIER_USER,
    # New section-rewrite prompts
    SECTION_REWRITE_SYSTEM,
    SECTION_REWRITE_USER,
    SECTION_REWRITE_SUMMARY_SYSTEM,
    SECTION_REWRITE_SUMMARY_USER,
)
from .loop4_editing import (
    LOOP4_ABSTRACT_EDITOR_SYSTEM,
    LOOP4_ABSTRACT_EDITOR_USER,
    LOOP4_FRAMING_EDITOR_SYSTEM,
    LOOP4_HOLISTIC_SYSTEM,
    LOOP4_HOLISTIC_USER,
    LOOP4_SECTION_EDITOR_SYSTEM,
    LOOP4_SECTION_EDITOR_USER,
    get_loop4_editor_prompts,
    TODO_RESOLUTION_SYSTEM,
    TODO_RESOLUTION_USER,
)
from .loop4_5_cohesion import LOOP4_5_COHESION_PROMPT
from .loop5_factcheck import (
    LOOP5_FACT_CHECK_SYSTEM,
    LOOP5_FACT_CHECK_USER,
    LOOP5_REF_CHECK_SYSTEM,
    LOOP5_REF_CHECK_USER,
)
from .shared import REVISION_SUMMARY_PROMPT

__all__ = [
    # Loop 1: Supervision
    "SUPERVISOR_SYSTEM",
    "SUPERVISOR_USER",
    "INTEGRATOR_SYSTEM",
    "INTEGRATOR_USER",
    # Loop 2: Literature
    "LOOP2_ANALYZER_SYSTEM",
    "LOOP2_ANALYZER_USER",
    "LOOP2_INTEGRATOR_SYSTEM",
    "LOOP2_INTEGRATOR_USER",
    # Loop 3: Structure
    "LOOP3_ANALYST_SYSTEM",
    "LOOP3_ANALYST_USER",
    "LOOP3_EDITOR_SYSTEM",
    "LOOP3_EDITOR_USER",
    "LOOP3_PHASE_A_SYSTEM",
    "LOOP3_PHASE_A_USER",
    "LOOP3_PHASE_B_SYSTEM",
    "LOOP3_PHASE_B_USER",
    "LOOP3_RETRY_SYSTEM",
    "LOOP3_VERIFIER_SYSTEM",
    "LOOP3_VERIFIER_USER",
    # Loop 3: Section rewrite (new approach)
    "SECTION_REWRITE_SYSTEM",
    "SECTION_REWRITE_USER",
    "SECTION_REWRITE_SUMMARY_SYSTEM",
    "SECTION_REWRITE_SUMMARY_USER",
    # Loop 4: Editing
    "LOOP4_SECTION_EDITOR_SYSTEM",
    "LOOP4_SECTION_EDITOR_USER",
    "LOOP4_HOLISTIC_SYSTEM",
    "LOOP4_HOLISTIC_USER",
    "LOOP4_ABSTRACT_EDITOR_SYSTEM",
    "LOOP4_ABSTRACT_EDITOR_USER",
    "LOOP4_FRAMING_EDITOR_SYSTEM",
    "get_loop4_editor_prompts",
    "TODO_RESOLUTION_SYSTEM",
    "TODO_RESOLUTION_USER",
    # Loop 4.5: Cohesion
    "LOOP4_5_COHESION_PROMPT",
    # Loop 5: Fact-checking
    "LOOP5_FACT_CHECK_SYSTEM",
    "LOOP5_FACT_CHECK_USER",
    "LOOP5_REF_CHECK_SYSTEM",
    "LOOP5_REF_CHECK_USER",
    # Shared
    "REVISION_SUMMARY_PROMPT",
]
